config/routes.rb
Rails.application.routes.draw do	
  root :to => "root#top"
  resources :posts
  delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
	post = Post.new(post_params)
	if post.save
       flash[:notice]= "Book was successfully updated."
	   redirect_to post_path(post.id)
    else
      render action: :new
    end
  end

  def index
  	@posts = Post.all
  	@post = Post.new
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	post = Post.find(params[:id])
  	if post.update(post_params)
       redirect_to post_path(post.id),notice: "Book was successfully updated."
    else
       render action: :new
    end
  end

  def destroy
  	post = Post.find(params[:id])
  	post.destroy
  	redirect_to '/posts'
  end

private

  def post_params
	params.require(:post).permit(:title, :body)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<%= f.submit 'Update Book' %>
	<% end %>

	<%= link_to "Show", Post.find(params[:id]), class: "show_#{@post.id}" %> 
	<%= link_to "Back", '/posts', class: "back"	%> 

app/views/posts/index.html.erb
<% if flash[:notice] %>
<P> <%=flash[:notice] %></P>
<% end %>

<h1>Book</h1>
<body>
	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Body</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<% @posts.each do |post| %>
		<tbody>
			<tr>
				<td> <%= post.title %> </td>
				<td> <%= post.body %> </td>
				<td> <%= link_to "Show", post_path(post.id), class: "show_#{post.id}" %> </td>
				<td> <%= link_to "Edit", edit_post_path(post.id), class: "edit_#{post.id}" %> </td>
				<td> <%= link_to "Destroy", destroy_post_path(post.id), class: "destroy_#{post.id}", method: :delete, "data-confirm" => "Are you sure?" %> </td>
			</tr>
			<% end %>
		</tbody>
	</table>

<h2>New book</h2>

<%= form_for(@post) do |f| %>

<h4>Title</h4>
<%= f.text_field :title, class: "book_title" %>

<h4>Body</h4>
<%= f.text_area :body, class: "book_body" %>

<%= f.submit 'Create Book' %>

<% end %>
</body>

app/views/posts/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>Title</p>
<p> <%= @post.title %> </p>
<p>Body</p>
<p> <%= @post.body %> </p>

<%= link_to "Edit", edit_post_path(@post.id),class: "edit_#{@post.id}" %>

<%= link_to 'Back', '/posts', class: "back" %> 

app/views/root/top.html.erb
<h1>ようこそ Bookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>印象を共有し交換することができます</p>

<a href ="/posts">start</a>